---
- hosts: localhost
  roles:
    - role: aws_startup
      tags: always
      
    - role: aws_create_bastion
      tags: always

    - role: aws_create_lambdas
      tags:
        - lambda

    - role: aws_create_database
      tags:
        - db
        - db_init

    - role: aws_create_wireguard_server
      tags: 
        - wg
        - wg_init

- import_playbook: playbooks/config_wireguard.yml
  tags:
    - wg
    - wg_config

- import_playbook: playbooks/config_database.yml
  vars:
    db: "{{ hostvars['localhost'].db }}"
  tags:
    - db
