---
- hosts: localhost
  pre_tasks:
    - name: Create new Network for Cloud TV Managment Project
      amazon.aws.ec2_vpc_net:
        name: Cloud TV Network
        cidr_block: 10.10.0.0/16
      register: tv_network

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ tv_network.vpc.id }}"
        tags:
          Name:  Cloud TV Internet Gateway
      register: igw

  roles:
    # - role: aws_create_database
    #   vars: 
    #     vpc_id: "{{ tv_network.vpc.id }}"
    #     allowed_subnets:
    #       - '10.10.1.0/24'
    
    - role: aws_create_wireguard_server
      vars: 
        vpc_id: "{{ tv_network.vpc.id }}"