---
- hosts: localhost
  roles:
    - role: aws_startup
      tags: always
      
    - role: aws_create_bastion
      tags: always

    # - role: aws_create_database

    - role: aws_create_wireguard_server
      tags: 
        - wg
        - wg_init

# - import_playbook: playbooks/config_wireguard.yml
#   tags:
#     - wg
#     - wg_config
