---
- name: Create Subnets
  amazon.aws.ec2_vpc_subnet:
    tags:
      Name: "TV Lambdas Subnet {{ item.name }}"
      Ansible: true
      Cloud-TV: true
    az: "{{ region }}{{ item.name }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.cidr }}"

  loop: "{{ az }}"
  register: subnets

- name: Add Subnets to Route Table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    lookup: id
    route_table_id: "{{ rt_def_id }}"
    purge_subnets: false
    purge_routes: false
    subnets: "{{ subnets.results | map(attribute='subnet.id') }}"

# - name: Add lambdas
#   amazon.aws.lambda:
#     name: '{{ item.name }}'
#     state: present
#     zip_file: '{{ item.zip_file }}'
#     runtime: 'python3.8'
#     role: 'arn:aws:iam::071163147552:role/LabRole'
#     handler: 'lambda_function.lambda_handler'
#     vpc_subnet_ids: "{{ subnets.results | map(attribute='subnet.id') }}"
#     vpc_security_group_ids:
#     - sg-05f20278fb998bfae
#     environment_variables: '{{ item.env_vars }}'
#     tags:
#       key1: 'value1'
#   loop:
#     - name: TVHealthcheck123
#       zip_file: tvhealthcheck.zip
#       env_vars:
#         db: "TV Database"
#         host_reader: "tv-database.cluster-ro-crwrdi5us9bm.us-east-1.rds.amazonaws.com"
#         host_writer: "tv-database.cluster-crwrdi5us9bm.us-east-1.rds.amazonaws.com"
#         password: "Password123"
#         username: "tvadmin"